### PR TITLE
Widen download window

### PR DESCRIPTION
**Pull request by gsanchietti**
Expand random cron wait to reduce load peaks from blacklist server.

### CODE REVIEW

**Comment by gsanchietti** [comment]
As an alternative approach, we could use `depth` option during the `pull` operation. Still, next pull could move the repo in an unrecoverable status. See also https://stackoverflow.com/questions/23986685/pull-updates-with-git-after-cloned-with-depth-1

**Review by DavidePrincipi — APPROVED** [review]
Ok to increase the randomness, but I like the alternative approach.

**Comment by DavidePrincipi** [comment]
> As an alternative approach, we could use `depth` option during the `pull` operation. Still, next pull could move the repo in an unrecoverable status. See also https://stackoverflow.com/questions/23986685/pull-updates-with-git-after-cloned-with-depth-1


If `git pull --depth X` fails, as suggested by the linked page, could the error be recovered with a `git pull --unshallow`? Or can we do `rm -f repo.git ; git clone --depth 1 repo.git` for every download?

**Review by Amygos — APPROVED** [review]

**Comment by gsanchietti** [comment]
Released: nethserver-blacklist-1.2.8-1.ns7.noarch.rpm

**Pull request merged**
